version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ActivityLog
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.data/db:/var/lib/postgresql/data

  webserver:
    restart: always
    volumes:
      - ./log_server:/app
      - ./scripts:/scripts
    build:
      context: .
      dockerfile: Dockerfile.app
    command: bash -c "python /scripts/wait_for_db.py && gunicorn -w 2 -b 0.0.0.0:8000 wsgi:app"
    ports:
      - 8000:8000
    depends_on:
      - db

  test-logging:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - "./test.py:/app/test.py"
    profiles: ["test"]
    command: bash -c "python test.py"
